[package]
name = "photobooth"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
drm = "0.14.1"
libc = "0.2.177"
libcamera = { version = "0.4.0", features = ["libcamera_semver_versioning", "vendor_rpi"], default-features = false }
ouroboros = "0.18.5"
